interface SafetyAnalysisReport {
  risk_level: string;
  overall_score: number;
  critical_issues: string[];
  recommendations: string[];
  compliance_status: string;
  action_items: string[];
  summary: string;
}

interface FinalJHAReport {
  metadata: {
    reportId: string;
    generatedAt: Date;
    projectName: string;
    location: string;
    workType: string;
    supervisor: string;
  };
  executiveSummary: {
    decision: any;
    overallRiskLevel: string;
    topThreats: string[];
    criticalActions: string[];
    incidentProbability: number;
  };
  dataQuality: {
    score: number;
    rating: string;
    missingCritical: string[];
    concerns: any[];
  };
  riskAssessment: {
    hazards: any[];
    industryContext: string;
    oshaStatistics: any;
  };
  incidentPrediction: {
    scenario: string;
    probability: number;
    timeframe: string;
    causalChain: any[];
    leadingIndicators: any;
  };
  weatherAnalysis: any;
  complianceGaps: any[];
  emergencyReadiness: any;
  actionItems: any[];
  recommendedInterventions: {
    preventive: string[];
    mitigative: string[];
  };
  approvals: {
    requiredSignatures: string[];
    competentPersonReview: boolean;
    managementReview: boolean;
  };
}

interface MultiModalAnalysisResult {
  overallRiskScore: number;
  blueprintAnalysis: {
    structuralHazards: string[];
    elevationRisks: string[];
    accessPoints: string[];
    safetyZones: string[];
    recommendations: string[];
  };
  visualPatternRecognition: {
    identifiedHazards: string[];
    equipmentDetected: string[];
    workerSafetyIssues: string[];
    environmentalFactors: string[];
  };
  integratedInsights: {
    criticalFindings: string[];
    complianceGaps: string[];
    immediateActions: string[];
    longTermRecommendations: string[];
  };
  insuranceRelevantData: {
    riskMitigationMeasures: string[];
    complianceScore: number;
    documentedSafetyPractices: string[];
    liabilityReduction: string[];
  };
}

export class ReportFormatter {
  static formatStandardSafetyReport(analysis: SafetyAnalysisReport, checklistTitle: string): string {
    const timestamp = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    return `# Safety Compliance Report

**Checklist:** ${checklistTitle}  
**Date:** ${timestamp}  
**Risk Level:** ${analysis.risk_level.toUpperCase()}  
**Overall Score:** ${analysis.overall_score}/100

---

## Executive Summary

${analysis.summary}

## Risk Assessment

**Risk Level:** ${analysis.risk_level.toUpperCase()}  
**Compliance Status:** ${analysis.compliance_status}

${analysis.risk_level === 'high' ? '⚠️ **IMMEDIATE ATTENTION REQUIRED**' : 
  analysis.risk_level === 'medium' ? '⚡ **MODERATE RISK IDENTIFIED**' : 
  '✅ **LOW RISK - GOOD PRACTICES OBSERVED**'}

---

## Critical Issues ${analysis.critical_issues.length > 0 ? `(${analysis.critical_issues.length})` : ''}

${analysis.critical_issues.length > 0 ? 
  analysis.critical_issues.map((issue, index) => `${index + 1}. **${issue}**`).join('\n') :
  '*No critical issues identified.*'}

---

## Immediate Action Items

${analysis.action_items.length > 0 ?
  analysis.action_items.map((item, index) => `- [ ] ${item}`).join('\n') :
  '*No immediate actions required.*'}

---

## Safety Recommendations

${analysis.recommendations.map((rec, index) => `### ${index + 1}. ${rec.split('.')[0] || rec.substring(0, 50)}

${rec}

`).join('')}

---

## Report Details

- **Generated by:** Safety Companion AI
- **Analysis Type:** Standard Safety Assessment
- **Report ID:** SC-${Date.now().toString(36)}
- **Next Review:** ${new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()}

---

*This report was generated using AI-powered safety analysis and should be reviewed by qualified safety personnel. For questions or clarifications, consult your safety manager.*`;
  }

  static formatMultiModalReport(analysis: MultiModalAnalysisResult, checklistTitle: string, blueprintCount: number, imageCount: number): string {
    const timestamp = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const riskLevel = analysis.overallRiskScore >= 80 ? 'HIGH' : 
                     analysis.overallRiskScore >= 60 ? 'MEDIUM' : 'LOW';
    
    const riskIcon = riskLevel === 'HIGH' ? '🔴' : 
                    riskLevel === 'MEDIUM' ? '🟡' : '🟢';

    return `# Comprehensive Multi-Modal Safety Analysis Report

**Project:** ${checklistTitle}  
**Date:** ${timestamp}  
**Analysis Type:** AI-Powered Multi-Modal Assessment  
**Risk Score:** ${analysis.overallRiskScore}/100 ${riskIcon}  
**Risk Level:** ${riskLevel}

---

## Analysis Overview

This comprehensive report combines AI analysis of:
- ✅ **Blueprint Analysis** (${blueprintCount} files)
- ✅ **Visual Recognition** (${imageCount} images)
- ✅ **Checklist Responses**
- ✅ **Railway System Integration**
- ✅ **Insurance Compliance Assessment**

---

## 🏗️ Blueprint Analysis Results

### Structural Hazards Identified
${analysis.blueprintAnalysis.structuralHazards.length > 0 ?
  analysis.blueprintAnalysis.structuralHazards.map(hazard => `- **${hazard}**`).join('\n') :
  '*No structural hazards identified in blueprints.*'}

### Elevation & Fall Risks
${analysis.blueprintAnalysis.elevationRisks.length > 0 ?
  analysis.blueprintAnalysis.elevationRisks.map(risk => `- ${risk}`).join('\n') :
  '*No significant elevation risks detected.*'}

### Access Points & Emergency Routes
${analysis.blueprintAnalysis.accessPoints.length > 0 ?
  analysis.blueprintAnalysis.accessPoints.map(point => `- ${point}`).join('\n') :
  '*Access points require review.*'}

### Safety Zones
${analysis.blueprintAnalysis.safetyZones.length > 0 ?
  analysis.blueprintAnalysis.safetyZones.map(zone => `- ${zone}`).join('\n') :
  '*Safety zones not clearly defined.*'}

---

## 📸 Visual Pattern Recognition

### Identified Hazards
${analysis.visualPatternRecognition.identifiedHazards.length > 0 ?
  analysis.visualPatternRecognition.identifiedHazards.map(hazard => `- ⚠️ **${hazard}**`).join('\n') :
  '*No visual hazards detected in uploaded images.*'}

### Equipment & PPE Analysis
${analysis.visualPatternRecognition.equipmentDetected.length > 0 ?
  analysis.visualPatternRecognition.equipmentDetected.map(equipment => `- ${equipment}`).join('\n') :
  '*Equipment detection analysis unavailable.*'}

### Worker Safety Issues
${analysis.visualPatternRecognition.workerSafetyIssues.length > 0 ?
  analysis.visualPatternRecognition.workerSafetyIssues.map(issue => `- 👷 **${issue}**`).join('\n') :
  '*No worker safety violations observed.*'}

### Environmental Factors
${analysis.visualPatternRecognition.environmentalFactors.length > 0 ?
  analysis.visualPatternRecognition.environmentalFactors.map(factor => `- 🌦️ ${factor}`).join('\n') :
  '*Environmental conditions appear acceptable.*'}

---

## 🎯 Critical Findings & Actions

### Immediate Actions Required
${analysis.integratedInsights.immediateActions.length > 0 ?
  analysis.integratedInsights.immediateActions.map((action, index) => `${index + 1}. **${action}**`).join('\n\n') :
  '*No immediate actions required.*'}

### Critical Findings
${analysis.integratedInsights.criticalFindings.length > 0 ?
  analysis.integratedInsights.criticalFindings.map(finding => `- 🔍 **${finding}**`).join('\n') :
  '*No critical findings identified.*'}

### Compliance Gaps
${analysis.integratedInsights.complianceGaps.length > 0 ?
  analysis.integratedInsights.complianceGaps.map(gap => `- 📋 ${gap}`).join('\n') :
  '*No significant compliance gaps identified.*'}

---

## 📈 Insurance & Risk Management

### Compliance Score: ${analysis.insuranceRelevantData.complianceScore}/100

### Risk Mitigation Measures
${analysis.insuranceRelevantData.riskMitigationMeasures.length > 0 ?
  analysis.insuranceRelevantData.riskMitigationMeasures.map(measure => `- ✅ ${measure}`).join('\n') :
  '*Additional risk mitigation measures recommended.*'}

### Documented Safety Practices
${analysis.insuranceRelevantData.documentedSafetyPractices.length > 0 ?
  analysis.insuranceRelevantData.documentedSafetyPractices.map(practice => `- 📝 ${practice}`).join('\n') :
  '*Safety documentation requires improvement.*'}

### Liability Reduction Opportunities
${analysis.insuranceRelevantData.liabilityReduction.length > 0 ?
  analysis.insuranceRelevantData.liabilityReduction.map(opportunity => `- 🛡️ ${opportunity}`).join('\n') :
  '*Continue current practices to maintain low liability.*'}

---

## 🔮 Long-Term Recommendations

${analysis.integratedInsights.longTermRecommendations.length > 0 ?
  analysis.integratedInsights.longTermRecommendations.map((rec, index) => `### ${index + 1}. ${rec.split(':')[0] || rec.substring(0, 40)}...

${rec}

`).join('') : '*No long-term recommendations at this time.*'}

---

## Blueprint Recommendations

${analysis.blueprintAnalysis.recommendations.length > 0 ?
  analysis.blueprintAnalysis.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n') :
  '*Blueprint analysis complete - no additional recommendations.*'}

---

## Report Summary

**Overall Assessment:** ${riskLevel} Risk Project  
**Compliance Score:** ${analysis.insuranceRelevantData.complianceScore}/100  
**Blueprint Files Analyzed:** ${blueprintCount}  
**Images Processed:** ${imageCount}  
**AI Confidence:** High (Multi-Modal Analysis)

### Next Steps
1. Review and address all immediate actions
2. Implement recommended safety measures
3. Schedule follow-up assessment in 30 days
4. Share report with insurance provider if applicable

---

## Report Details

- **Generated by:** Safety Companion AI (Multi-Modal)
- **Report ID:** SC-MM-${Date.now().toString(36)}
- **Analysis Engine:** Gemini AI + Pattern Recognition
- **Next Review:** ${new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()}
- **Export Options:** PDF, Email, Database Storage

---

*This comprehensive report was generated using advanced AI analysis combining blueprint pattern recognition, visual hazard detection, and regulatory compliance assessment. This report is designed for insurance documentation and regulatory compliance. For technical questions, consult your project safety manager.*`;
  }

  static formatForEmail(report: string, subject: string): { subject: string; body: string } {
    return {
      subject: `Safety Report: ${subject} - ${new Date().toLocaleDateString()}`,
      body: `Dear Safety Team,

Please find the attached safety analysis report generated by our AI-powered Safety Companion system.

${report}

Best regards,
Safety Companion System

---
This is an automated report. Please do not reply to this email.`
    };
  }

  static formatForSharing(report: string): string {
    // Add sharing metadata and remove sensitive internal details
    const sharingHeader = `# Safety Analysis Report - Shared Copy

> **Shared on:** ${new Date().toLocaleDateString('en-US', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric', 
  hour: '2-digit', 
  minute: '2-digit' 
})}  
> **Generated by:** Safety Companion AI  
> **Status:** Professional Safety Assessment

---

`;
    
    return sharingHeader + report;
  }

  static formatForDatabase(report: string, checklistId: string, userId: string): any {
    return {
      id: `report_${Date.now()}`,
      checklist_id: checklistId,
      user_id: userId,
      report_type: 'ai_analysis',
      content: report,
      formatted_content: report, // Already in markdown
      generated_at: new Date().toISOString(),
      status: 'active',
      sharing_enabled: true,
      export_formats: ['pdf', 'email', 'markdown'],
      metadata: {
        word_count: report.split(' ').length,
        has_critical_issues: report.includes('CRITICAL') || report.includes('HIGH'),
        compliance_ready: true,
        insurance_compatible: true
      }
    };
  }

  static formatStructuredJHAReport(report: FinalJHAReport): string {
    const timestamp = new Date(report.metadata.generatedAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const decisionIcon = report.executiveSummary.decision.decision === 'GO' ? '✅' :
                        report.executiveSummary.decision.decision === 'GO_WITH_CONDITIONS' ? '⚠️' : '🛑';

    return `# Predictive Job Hazard Analysis Report

**Project:** ${report.metadata.projectName}  
**Location:** ${report.metadata.location}  
**Work Type:** ${report.metadata.workType}  
**Supervisor:** ${report.metadata.supervisor}  
**Date:** ${timestamp}  
**Report ID:** ${report.metadata.reportId}

---

## Executive Decision: ${decisionIcon} ${report.executiveSummary.decision.decision}

**Overall Risk Level:** ${report.executiveSummary.overallRiskLevel}  
**Incident Probability (Next 4 Hours):** ${(report.executiveSummary.incidentProbability * 100).toFixed(1)}%

${report.executiveSummary.decision.reasons.length > 0 ? `
### Decision Reasons:
${report.executiveSummary.decision.reasons.map((r: string) => `- ${r}`).join('\n')}
` : ''}

${report.executiveSummary.decision.conditions.length > 0 ? `
### Required Conditions:
${report.executiveSummary.decision.conditions.map((c: string) => `- ✓ ${c}`).join('\n')}
` : ''}

### Top Threats Identified:
${report.executiveSummary.topThreats.map((threat: string) => `- ${threat}`).join('\n')}

### Critical Actions Required:
${report.executiveSummary.criticalActions.length > 0 ?
  report.executiveSummary.criticalActions.map((action: string) => `- **${action}**`).join('\n') :
  '*No critical actions required.*'}

---

## Data Quality Assessment

**Quality Score:** ${report.dataQuality.score}/10  
**Rating:** ${report.dataQuality.rating}

${report.dataQuality.missingCritical.length > 0 ? `
### Missing Critical Information:
${report.dataQuality.missingCritical.map((item: string) => `- ⚠️ ${item}`).join('\n')}
` : ''}

${report.dataQuality.concerns.length > 0 ? `
### Data Quality Concerns:
${report.dataQuality.concerns.slice(0, 5).map((concern: any) => 
  `- **[${concern.severity}]** ${concern.concern}`
).join('\n')}
` : ''}

---

## Risk Assessment

**Industry Context:** ${report.riskAssessment.industryContext}

${report.riskAssessment.oshaStatistics ? `
### OSHA Statistics (BLS 2023):
- **Industry:** ${report.riskAssessment.oshaStatistics.industryName}
- **NAICS Code:** ${report.riskAssessment.oshaStatistics.naicsCode}
- **Injury Rate:** ${report.riskAssessment.oshaStatistics.injuryRate} per 100 workers
` : ''}

### Identified Hazards:
${report.riskAssessment.hazards.slice(0, 5).map((hazard: any, i: number) => `
#### ${i + 1}. ${hazard.name} (Risk Score: ${hazard.riskScore}/100)

**Probability:** ${(hazard.probability * 100).toFixed(1)}%  
**Consequence:** ${hazard.consequence}  
**Category:** ${hazard.category || 'General'}

${hazard.oshaContext ? `**OSHA Context:** ${hazard.oshaContext}` : ''}

${hazard.inadequateControls && hazard.inadequateControls.length > 0 ? `
**Inadequate Controls:**
${hazard.inadequateControls.map((ctrl: string) => `- ${ctrl}`).join('\n')}
` : ''}

${hazard.recommendedControls && hazard.recommendedControls.length > 0 ? `
**Recommended Controls:**
${hazard.recommendedControls.map((ctrl: string) => `- ${ctrl}`).join('\n')}
` : ''}
`).join('\n')}

---

## Incident Prediction (Swiss Cheese Model)

**Predicted Scenario:** ${report.incidentPrediction.scenario}  
**Timeframe:** ${report.incidentPrediction.timeframe}  
**Probability:** ${(report.incidentPrediction.probability * 100).toFixed(1)}%

### Causal Chain Analysis:
${report.incidentPrediction.causalChain.map((stage: any, i: number) => `
**${i + 1}. ${stage.stage}**  
${stage.description}
${stage.evidence ? `\n*Evidence:* ${stage.evidence}` : ''}
${stage.intervention ? `\n*Intervention:* ${stage.intervention}` : ''}
`).join('\n')}

${report.incidentPrediction.leadingIndicators ? `
### Leading Indicators Present:
${Object.entries(report.incidentPrediction.leadingIndicators).map(([category, indicators]: [string, any]) => `
**${category}:**
${Array.isArray(indicators) ? indicators.map((ind: string) => `- ${ind}`).join('\n') : indicators}
`).join('\n')}
` : ''}

---

## Weather Impact Analysis

${report.weatherAnalysis ? `
**Status:** ${report.weatherAnalysis.status}  
**Impact:** ${report.weatherAnalysis.impact}

${report.weatherAnalysis.risks && report.weatherAnalysis.risks.length > 0 ? `
### Weather Risks:
${report.weatherAnalysis.risks.map((risk: string) => `- ${risk}`).join('\n')}
` : ''}

${report.weatherAnalysis.recommendations && report.weatherAnalysis.recommendations.length > 0 ? `
### Recommendations:
${report.weatherAnalysis.recommendations.map((rec: string) => `- ${rec}`).join('\n')}
` : ''}
` : '*Weather analysis unavailable.*'}

---

## Compliance Gaps

${report.complianceGaps.length > 0 ? 
  report.complianceGaps.map((gap: any) => `
### ${gap.standard || 'Compliance Issue'}
**Severity:** ${gap.severity}  
**Gap:** ${gap.gap}  
${gap.correctiveAction ? `**Corrective Action:** ${gap.correctiveAction}` : ''}
`).join('\n') : 
  '*No compliance gaps identified.*'}

---

## Emergency Readiness Assessment

${report.emergencyReadiness ? `
**Status:** ${report.emergencyReadiness.status}  
**Adequacy:** ${report.emergencyReadiness.adequacy}

${report.emergencyReadiness.gaps && report.emergencyReadiness.gaps.length > 0 ? `
### Gaps:
${report.emergencyReadiness.gaps.map((gap: string) => `- ${gap}`).join('\n')}
` : ''}

${report.emergencyReadiness.requiredEquipment && report.emergencyReadiness.requiredEquipment.length > 0 ? `
### Required Equipment:
${report.emergencyReadiness.requiredEquipment.map((eq: string) => `- ${eq}`).join('\n')}
` : ''}
` : '*Emergency readiness assessment unavailable.*'}

---

## Action Items

${report.actionItems.length > 0 ?
  report.actionItems.map((item: any, i: number) => `
### ${i + 1}. [${item.priority}] ${item.action}

**Timeline:** ${item.timeline}  
**Responsible Party:** ${item.responsibleParty}
${item.verification ? `**Verification Method:** ${item.verification}` : ''}
`).join('\n') :
  '*No action items required.*'}

---

## Recommended Interventions

### Preventive Measures:
${report.recommendedInterventions.preventive.length > 0 ?
  report.recommendedInterventions.preventive.map((measure: string) => `- ${measure}`).join('\n') :
  '*No preventive measures recommended.*'}

### Mitigative Measures:
${report.recommendedInterventions.mitigative.length > 0 ?
  report.recommendedInterventions.mitigative.map((measure: string) => `- ${measure}`).join('\n') :
  '*No mitigative measures recommended.*'}

---

## Required Approvals & Sign-offs

${report.approvals.requiredSignatures.length > 0 ? `
### Required Signatures:
${report.approvals.requiredSignatures.map((sig: string) => `- [ ] ${sig}`).join('\n')}
` : ''}

- ${report.approvals.competentPersonReview ? '[x]' : '[ ]'} Competent Person Review Required
- ${report.approvals.managementReview ? '[x]' : '[ ]'} Management Review Required

---

## Report Details

- **Generated by:** Safety Companion AI - Multi-Agent Pipeline
- **Analysis Type:** Predictive Job Hazard Analysis
- **Agent Pipeline:** 4-Agent System (Validator → Risk Assessor → Incident Predictor → Report Synthesizer)
- **Data Sources:** OSHA BLS 2023, Real-time Weather, Site Checklist
- **Next Review:** ${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}

---

*This predictive analysis combines traditional Job Hazard Analysis with AI-powered incident forecasting using the Swiss Cheese causation model. Review all recommendations with qualified safety personnel before proceeding with work.*`;
  }
}